config/routes.rb
Rails.application.routes.draw do
  # Set list of channels as homepage
  root "channels#index"
  resources :channels do 
    resources :entries
  end

  get "/about", to: "application#about"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :entries, dependent: :destroy
  
  validates :name, presence: true
  validates :url, presence: true
  validates :description, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :channel
  validates :title, presence: true, uniqueness: { scope: :channel_id }
  validates :content, presence: true
end

app/models/scraper.rb
class Scraper
  def self.scrape_entries(channel)
    xml = HTTParty.get(channel.url).body
    feed = Feedjira.parse(xml)
    new_entries = feed.entries.filter_map {|entry| channel.entries.exists?(:title => entry.title) ? nil : entry}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def about
    render "/about"
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  after_action :ingest_entries, only: [:create, :update]

  def index
    @channels = Channel.all
  end

  def show 
    @channel = Channel.find(params[:id])
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)

    if @channel.save
      redirect_to @channel
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @channel = Channel.find(params[:id])
  end

  def update
    @channel = Channel.find(params[:id])

    if @channel.update(Channel_params)
      ingest_entries
      redirect_to @channel
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy
    # TODO: Remove the entries associated with the channel? 
    redirect_to root_path, status: :see_other
  end

  private 
    def channel_params
      params.require(:channel).permit(:name, :url, :description, :image)
    end

    def ingest_entries
      @entries = Scraper.scrape_entries(@channel)
      @entries.each do |entry|
        copy = entry[:summary] || entry[:content] || "No summary available."
        link = entry[:url] || entry[:enclosure_url]
        Entry.create(title: entry[:title], published: entry[:published], content: copy, url: link, author: entry[:author], read: false, channel_id: @channel.id)
      end
      puts "Entries ingested", @entries.count
    end

end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  def create
    @channel = Channel.find(params[:channel_id])
    @entry = @channel.entries.create(entry_params)
    redirect_to channel_path(@channel)
  end

  def update
    title = params[:title]
    is_read = ActiveRecord::Type::Boolean.new.cast(params[:read])
    if Entry.update(params[:channel_id], title: params[:title], read: is_read)
      puts params, is_read, title
      puts 'updated'
      @channel = Channel.find(params[:id])
      redirect_to channel_path(@channel)
    else 
      puts 'not updated'
      render :edit, status: :unprocessable_entity
    end
  end

  private 
    def entry_params
      if params[:read].is_a?(String)
        params[:read] = params[:read] == "true"
      else
        params.require(:title).permit(:published, :content, :url, :author, :read, :channel_id)
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/channels/_channelform.html.erb
<div class="space-y-12">
  <div class="border-gray-900/10 pb-12">

  <%= form_with model: channel do |form| %>
    <div class="w-full md:w-auto">
      <%= form.label :name, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :name, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
      <% @channel.errors.full_messages_for(:name).each do |message| %>
        <div class="text-braven-red"><%= message %></div>
      <% end %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.label :url, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :url, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
      <% @channel.errors.full_messages_for(:url).each do |message| %>
        <div class="text-braven-red"><%= message %></div>
      <% end %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.label :description, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :description, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
      <% @channel.errors.full_messages_for(:description).each do |message| %>
        <div class="text-braven-red"><%= message %></div>
      <% end %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.label :image, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :image, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.submit :class => "leading-6 rounded-full bg-braven-red px-4 py-2.5 text-sm text-font-semibold text-white shadow-sm hover:bg-transparent hover:outline hover:outline-braven-red hover:text-braven-red hover-outline-2 grid grid-cols-2 gap-x-1" %>
    </div>

  <% end %>

  </div>
</div>

app/views/channels/_form.html.erb
<div class="space-y-12">
  <div class="border-gray-900/10 pb-12">

  <%= form_with model: channel do |form| %>
    <div class="w-full md:w-auto">
      <%= form.label :name, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :name, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
      <% @channel.errors.full_messages_for(:name).each do |message| %>
        <div class="text-braven-red"><%= message %></div>
      <% end %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.label :url, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :url, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
      <% @channel.errors.full_messages_for(:url).each do |message| %>
        <div class="text-braven-red"><%= message %></div>
      <% end %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.label :description, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :description, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
      <% @channel.errors.full_messages_for(:description).each do |message| %>
        <div class="text-braven-red"><%= message %></div>
      <% end %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.label :image, :class => "block text-sm font-medium leading-6 text-gray-900" %>
      <%= form.text_field :image, :class => "block flex-1 border-1 bg-transparent py-1.5 pl-1 text-gray-900 placeholder:text-gray-400 focus:ring-0 w-full" %>
    </div>

    <div class="w-full md:w-auto mt-8">
      <%= form.submit :class => "leading-6 rounded-full bg-braven-red px-4 py-2.5 text-sm text-font-semibold text-white shadow-sm hover:bg-transparent hover:outline hover:outline-braven-red hover:text-braven-red hover-outline-2 grid grid-cols-2 gap-x-1" %>
    </div>

  <% end %>

  </div>
</div>

app/views/channels/edit.html.erb
<div class="overflow-hidden rounded-lg bg-white">
  <div class="px-4 py-5 sm:px-6 grid grid-cols-2">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Edit Channel</h2> 
  </div>
  <div class="px-4 py-5 sm:px-6
    <%= render "channelform", channel: @channel %>
  </div>
</div>

app/views/channels/index.html.erb
<div class="bg-white">
  <div class="mx-auto max-w-7xl px-6 lg:px-8">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Channels</h2>
    <p class="mt-2 text-lg leading-8 text-gray-600">Current RSS feed subscriptions</p>
    <ul role="list" class="mt-10 grid grid-cols-2 gap-x-4 gap-y-8 sm:grid-cols-3 sm:gap-x-6 lg:grid-cols-4 xl:gap-x-8">
      <% @channels.each do |channel| %>
        <li class="relative">
          <div class="group block w-full overflow-hidden rounded-lg bg-gray-100 focus-within:ring-2 focus-within:ring-indigo-500 focus-within:ring-offset-2 focus-within:ring-offset-gray-100">
            <img src="<%=channel.image%>" alt="<%=channel.name%>" class="w-80 aspect-[1/1] pointer-events-none group-hover:opacity-75 object-cover">
            <a class="button absolute inset-0 focus:outline-none" href="<%= channel_path(channel) %>" alt="<%=channel.name%> link" >
              <span class="text-transparent"><%= channel.name %></span>
            </a>
          </div>
          <p class="pointer-events-none mt-2 block truncate text-sm font-semi-bold text-gray-900"><%=channel.name %></p>
          <p class="pointer-events-none block text-sm font-medium text-gray-500"><%=channel.description %></p>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/channels/new.html.erb
<div class="overflow-hidden rounded-lg bg-white">
  <div class="px-4 py-5 sm:px-6 grid grid-cols-2">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Create New Channel</h2> 
  </div>
  <div class="px-4 py-5 sm:px-6
    <%= render "channelform", channel: @channel %>
  </div>
</div>

app/views/channels/show.html.erb
<div class="overflow-hidden rounded-lg bg-white">
  <div class="px-4 py-5 sm:px-6 flex flex-row space-between align-center">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl"><%= @channel.name %></h2>
    <span class="isolate inline-flex rounded-md shadow-sm px-8">
      <%= link_to edit_channel_path(@channel) do %>
        <button type="button" class="relative inline-flex items-center rounded-l-md bg-braven-red px-3 py-2 text-sm font-semibold text-white ring-1 ring-inset ring-white hover:bg-black focus:z-10">Edit</button>
      <% end %>
      <%= link_to channel_path(@channel), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure you want to delete this channel?"
        } do %>
        <button type="button" class="relative -ml-px inline-flex items-center bg-braven-red px-3 py-2 text-sm font-semibold text-white ring-1 ring-inset ring-white hover:bg-black focus:z-10">Delete</button>
      <% end %>
      <%= link_to channel_path(@channel), method: 'put' do %>
        <button type="button" class="relative -ml-px inline-flex items-center rounded-r-md bg-braven-red px-3 py-2 text-sm font-semibold text-white ring-1 ring-inset ring-white hover:bg-black focus:z-10">Refresh</button>
      <% end %>
    </span>
  </div>
  <div class="px-4 py-5 sm:p-6">
    <img src="<%= @channel.image%>" alt="<%= @channel.name%>" class="pointer-events-none object-cover group-hover:opacity-75 max-w-sm">
  </div>
  <div class="px-4 py-4 sm:px-6">
    <p class="text-lg leading-8 text-gray-600"><%= @channel.description %></p>
  </div>
  <div class="px-4 py-5 sm:px-6">
    <h2 class="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Episodes</h2>
    <ul role="list" class="divide-y divide-gray-100 w-full">
    <% @channel.entries.each do |entry| %>
      <li class="<%= entry.read == true ? 'flex justify-between gap-x-6 py-5' : 'flex justify-between gap-x-6 py-5 bg-gray-100' %>">
        <div class="flex min-w-0 gap-x-4 items-center">
          <div class="flex h-6 items-center">
            <% if entry.read %>
              <%= button_to "Mark as Unread", channel_entry_path(entry), method: :patch, params: { title: entry.title, read: false }, class: "text-xs leading-5 text-gray-500 hover:text-braven-red" %>
            <% else %>
              <%= button_to "Mark as Read", channel_entry_path(entry), method: :patch, params: { title: entry.title, read: true }, class: "text-xs leading-5 text-gray-500 hover:text-braven-red" %>
            <% end %>            
          </div>
          <img class="h-12 w-12 flex-none rounded-full bg-gray-50" src="<%= @channel.image %>" alt="<%= @channel.name %>">
          <div class="min-w-0 flex-auto">
            <p class="text-sm font-semibold leading-6 text-gray-900"><%= entry.title %></p>
            <p class="mt-1 truncate text-xs leading-5 text-gray-500"><%= entry.content ? entry.content.truncate(100, omission: '... (click for more)') : "" %></p>
          </div>
        </div>
        <div class="hidden shrink-0 sm:flex sm:flex-col sm:items-end">
          <p class="text-sm leading-6 text-gray-900"><%= entry.published ? entry.published.localtime : "" %></p>
          <p class="mt-1 text-xs leading-5 text-gray-500"><%= entry.author || 'Staff' %></p>
        </div>
      </li>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BravenRss</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="font-serif">
    <header class="bg-braven-black">
    <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
      <div class="flex lg:flex-1">
        <a href="#" class="-m-1.5 p-1.5">
          <span class="sr-only">Braven RSS</span>
          <%= image_tag("logo-braven.svg", :alt => "braven logo", :class => "h-8 w-auto") %>
        </a>
      </div>
      <div class="hidden lg:flex lg:gap-x-12 text-white">
        <a href="/channels" class="text-sm font-semibold leading-6 hover:text-braven-red">Channels</a>
        <a href="/about" class="text-sm font-semibold leading-6 hover:text-braven-red">About</a>
      </div>
      <div class="hidden lg:flex lg:flex-1 lg:justify-end">
        <%= link_to new_channel_path do %>
          <button type="button" class="leading-6 rounded-full bg-braven-red px-4 py-2.5 text-sm text-font-semibold text-white shadow-sm hover:bg-transparent hover:outline hover:outline-braven-red hover-outline-2 grid grid-cols-2 gap-x-1">Add
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v6m3-3H9m12 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
          </svg>
        </button>
        <% end %>
      </div>
    </nav>
  </header>
    <main class="container mx-auto my-10 px-5 flex">
      <%= yield %>
    </main>
    <footer class="bg-braven-beige">
      <div class="mx-auto max-w-7xl overflow-hidden px-6 py-20 sm:py-24 lg:px-8">
        <nav class="-mb-6 columns-2 sm:flex sm:justify-center sm:space-x-12" aria-label="Footer">
          <div class="pb-6">
            <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">About</a>
          </div>
          <div class="pb-6">
            <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Blog</a>
          </div>
          <div class="pb-6">
            <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Jobs</a>
          </div>
          <div class="pb-6">
            <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Press</a>
          </div>
          <div class="pb-6">
            <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Accessibility</a>
          </div>
          <div class="pb-6">
            <a href="#" class="text-sm leading-6 text-gray-600 hover:text-gray-900">Partners</a>
          </div>
        </nav>
        <div class="mt-10 flex justify-center space-x-10">
          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">Facebook</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M22 12c0-5.523-4.477-10-10-10S2 6.477 2 12c0 4.991 3.657 9.128 8.438 9.878v-6.987h-2.54V12h2.54V9.797c0-2.506 1.492-3.89 3.777-3.89 1.094 0 2.238.195 2.238.195v2.46h-1.26c-1.243 0-1.63.771-1.63 1.562V12h2.773l-.443 2.89h-2.33v6.988C18.343 21.128 22 16.991 22 12z" clip-rule="evenodd" />
            </svg>
          </a>
          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">Instagram</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12.315 2c2.43 0 2.784.013 3.808.06 1.064.049 1.791.218 2.427.465a4.902 4.902 0 011.772 1.153 4.902 4.902 0 011.153 1.772c.247.636.416 1.363.465 2.427.048 1.067.06 1.407.06 4.123v.08c0 2.643-.012 2.987-.06 4.043-.049 1.064-.218 1.791-.465 2.427a4.902 4.902 0 01-1.153 1.772 4.902 4.902 0 01-1.772 1.153c-.636.247-1.363.416-2.427.465-1.067.048-1.407.06-4.123.06h-.08c-2.643 0-2.987-.012-4.043-.06-1.064-.049-1.791-.218-2.427-.465a4.902 4.902 0 01-1.772-1.153 4.902 4.902 0 01-1.153-1.772c-.247-.636-.416-1.363-.465-2.427-.047-1.024-.06-1.379-.06-3.808v-.63c0-2.43.013-2.784.06-3.808.049-1.064.218-1.791.465-2.427a4.902 4.902 0 011.153-1.772A4.902 4.902 0 015.45 2.525c.636-.247 1.363-.416 2.427-.465C8.901 2.013 9.256 2 11.685 2h.63zm-.081 1.802h-.468c-2.456 0-2.784.011-3.807.058-.975.045-1.504.207-1.857.344-.467.182-.8.398-1.15.748-.35.35-.566.683-.748 1.15-.137.353-.3.882-.344 1.857-.047 1.023-.058 1.351-.058 3.807v.468c0 2.456.011 2.784.058 3.807.045.975.207 1.504.344 1.857.182.466.399.8.748 1.15.35.35.683.566 1.15.748.353.137.882.3 1.857.344 1.054.048 1.37.058 4.041.058h.08c2.597 0 2.917-.01 3.96-.058.976-.045 1.505-.207 1.858-.344.466-.182.8-.398 1.15-.748.35-.35.566-.683.748-1.15.137-.353.3-.882.344-1.857.048-1.055.058-1.37.058-4.041v-.08c0-2.597-.01-2.917-.058-3.96-.045-.976-.207-1.505-.344-1.858a3.097 3.097 0 00-.748-1.15 3.098 3.098 0 00-1.15-.748c-.353-.137-.882-.3-1.857-.344-1.023-.047-1.351-.058-3.807-.058zM12 6.865a5.135 5.135 0 110 10.27 5.135 5.135 0 010-10.27zm0 1.802a3.333 3.333 0 100 6.666 3.333 3.333 0 000-6.666zm5.338-3.205a1.2 1.2 0 110 2.4 1.2 1.2 0 010-2.4z" clip-rule="evenodd" />
            </svg>
          </a>
          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">X</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path d="M13.6823 10.6218L20.2391 3H18.6854L12.9921 9.61788L8.44486 3H3.2002L10.0765 13.0074L3.2002 21H4.75404L10.7663 14.0113L15.5685 21H20.8131L13.6819 10.6218H13.6823ZM11.5541 13.0956L10.8574 12.0991L5.31391 4.16971H7.70053L12.1742 10.5689L12.8709 11.5655L18.6861 19.8835H16.2995L11.5541 13.096V13.0956Z" />
            </svg>
          </a>
          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">GitHub</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z" clip-rule="evenodd" />
            </svg>
          </a>
          <a href="#" class="text-gray-400 hover:text-gray-500">
            <span class="sr-only">YouTube</span>
            <svg class="h-6 w-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true">
              <path fill-rule="evenodd" d="M19.812 5.418c.861.23 1.538.907 1.768 1.768C21.998 8.746 22 12 22 12s0 3.255-.418 4.814a2.504 2.504 0 0 1-1.768 1.768c-1.56.419-7.814.419-7.814.419s-6.255 0-7.814-.419a2.505 2.505 0 0 1-1.768-1.768C2 15.255 2 12 2 12s0-3.255.417-4.814a2.507 2.507 0 0 1 1.768-1.768C5.744 5 11.998 5 11.998 5s6.255 0 7.814.418ZM15.194 12 10 15V9l5.194 3Z" clip-rule="evenodd" />
            </svg>
          </a>
        </div>
        <p class="mt-10 text-center text-xs leading-5 text-gray-500">&copy; 2024 Braven RSS. All rights reserved.</p>
      </div>
    </footer>

  </body>
</html>